### ISSUE TITLE
Mouse move function

### ISSUE THREAD

**Issue by MetalBlueberry** [bendahl/uinput#21]
I've noticed that in the last commit you prevent Move* functions from accepting negative values. I understand the reason and I agree.

The problem is that when you calculate mouse movement, usually the left/right or up/down movements are represented as negative/positive values. With this change, you force the users to do something like this

```go
func horizontalMove(value int32) {
 if > 0 {
  MoveRight(value)
 }else{
  MoveLeft(-value)
 }
}
```
So, I wonder if it could be possible to have a generic method to move the cursor based on x,y coordinates no matter the direction.

```go
func Move(x, y int32) error
```

**Comment by bendahl** [comment]
Hi there!

thanks for taking the time to take a closer look at the library and pointing this out. I think I get your point. The current API was meant to be expressive, but can be a little clunky to use at times. Agreed. In terms of effort it shouldn't be a big deal to implement a more generic method. I'll take a look at this.

Cheers,
Ben
