### ISSUE TITLE
Absolute movement not working. 

### ISSUE THREAD

**Issue by sm177y23** [bendahl/uinput#22]
Your examples and code suggest that one should be able to move the cursor to an exact location by using a touchpad but I am unable to get this to work. In fact touchpad.MoveTo does nothing for me but the clicks work fine and if I make a mouse instead, the relative movements work too. 
I am curious if a touchpad is even capable of absolute movement this way. When I dump the events of my own touchpad with libinput for example, they are basically the same as a mouse, only relative movement values are given in the events.
Can absolute movement be done with this or am I stuck having to use robotgo for movement? Which from what I can tell is importing some C just to do the absolute movement. I would like to use one or the other but robotgo's clicking doesn't work right for me either... Go figure..

**Comment by bendahl** [comment]
Hi there,

thanks for the info. I just double checked the issue you've raised, since I haven't done any work on the touchpad part for some time. I'm running into the same issue though, so I will have to investigate this further. Once I know more, I will update this issue. 

Cheers,
Ben

**Comment by mafredri** [comment]
It looks like there are two ways to make the virtual touchpad work:

1. Remove `evBtnToolFinger` from https://github.com/bendahl/uinput/blob/ba90e5533751e1302a7dbea84b7e9c1d14d45102/touchpad.go#L138
2. Issue `tp.TouchDown()` before `tp.MoveTo(x, y)` (followed by a `tp.TouchUp()` after some time has elapsed, I suppose)

Interestingly, these two options behave very differently. In option 1. `MoveTo(x, y)` behaves as you would expect, the mouse moves to those coordinates.

In option 2. however, the mouse movement seems to obey acceleration. I.e. the cursor will not go to the specified coordinates, slow movements may only bring it half-way there. This is pretty similar to how the virtual mouse behaves (except you don't need to track previous coordinates with the touchpad).

**Comment by bendahl** [comment]
Hi Mathias,

great catch! I think that for the purpose of this library option number one is the way to go, as it does what one would expect. I will make sure to fix this. Thanks for sharing your findings. Interesting indeed...

Cheers,
Ben
