### ISSUE TITLE
The examples above v1.1.1 are invalid

### ISSUE THREAD

**Issue by Makima0** [bendahl/uinput#23]

**Comment by bendahl** [comment]
Hi there,

can you explain which examples aren't working for you and in which scenario? I'm not sure if I understand what the issue is. It would be great if you could describe what's not working for you, so that I can reproduce the problem. Thanks in advance!

Cheers
Ben

**Comment by Makima0** [comment]
> Hi there,
> 
> can you explain which examples aren't working for you and in which scenario? I'm not sure if I understand what the issue is. It would be great if you could describe what's not working for you, so that I can reproduce the problem. Thanks in advance!
> 
> Cheers
> Ben

Sorry to interrupt you, anyway, now the examples can run as expected, it’s my problem. 
XD
I will close this issue.
wish you a happy life.
