### ISSUE TITLE
Issue with Example

### ISSUE THREAD

**Issue by patrickcorrigan** [bendahl/uinput#25]
I've created a virtual keyboard

I can see the input device in `/sys/devices/virtual/input`

as input7

The key presses don't seem to be registered.

From what I can tell it's not showing up in `xinput -list`

Looking at `input7` directory in `/sys/devices/virtual/input` I could see a directory `event4`

Using `evtest` I can see the keyboard events are being generated successfully.
```
Event: time 1624187132.489135, type 1 (EV_KEY), code 45 (KEY_X), value 1
Event: time 1624187132.489135, -------------- SYN_REPORT ------------
Event: time 1624187134.489502, type 1 (EV_KEY), code 45 (KEY_X), value 0
Event: time 1624187134.489502, -------------- SYN_REPORT ------------
Event: time 1624187134.681998, type 1 (EV_KEY), code 45 (KEY_X), value 1
Event: time 1624187134.681998, -------------- SYN_REPORT ------------
Event: time 1624187136.682230, type 1 (EV_KEY), code 45 (KEY_X), value 0
Event: time 1624187136.682230, -------------- SYN_REPORT ------------
Event: time 1624187136.682537, type 1 (EV_KEY), code 45 (KEY_X), value 1
Event: time 1624187136.682537, -------------- SYN_REPORT ------------
Event: time 1624187138.683337, type 1 (EV_KEY), code 45 (KEY_X), value 0
Event: time 1624187138.683337, -------------- SYN_REPORT ------------
Event: time 1624187138.683697, type 1 (EV_KEY), code 45 (KEY_X), value 1
Event: time 1624187138.683697, -------------- SYN_REPORT ------------
Event: time 1624187140.684101, type 1 (EV_KEY), code 45 (KEY_X), value 0
Event: time 1624187140.684101, -------------- SYN_REPORT ------------
Event: time 1624187144.894104, type 1 (EV_KEY), code 45 (KEY_X), value 1
Event: time 1624187144.894104, -------------- SYN_REPORT ------------
Event: time 1624187146.895425, type 1 (EV_KEY), code 45 (KEY_X), value 0
Event: time 1624187146.895425, -------------- SYN_REPORT ------------
```
But they're not being passed to xwindows - I'm thinking of trying to add it manually but am I doing something wrong or missing something simple :)

Looking at dmesg I can see the input being created

`input: testkeyboard as /devices/virtual/input/input7`

**Comment by bendahl** [comment]
Hi Patrick,

I've just had a look at this, but haven't been able to reproduce the issue. Here is the code I used to try and reproduce what you've described:

```go
func TestKeyXWorks(t *testing.T) {
	vk, err := CreateKeyboard("/dev/uinput", []byte("Test Basic Keyboard"))
	if err != nil {
		t.Fatalf("Failed to create the virtual keyboard. Last error was: %s\n", err)
	}

	err = vk.KeyDown(KeyX)
	if err != nil {
		t.Fatalf("Failed to send key down event. Last error was: %s\n", err)
	}

	err = vk.KeyUp(KeyX)
	if err != nil {
		t.Fatalf("Failed to send key up event. Last error was: %s\n", err)
	}

	err = vk.Close()

	if err != nil {
		t.Fatalf("Failed to close device. Last error was: %s\n", err)
	}
}
```
The above test will create a keyboard and lead to 'x' being printed.

Output generated by evtest (excerpt):
```
Testing ... (interrupt to exit)
Event: time 1624468314.531984, type 1 (EV_KEY), code 45 (KEY_X), value 1
Event: time 1624468314.531984, -------------- SYN_REPORT ------------
Event: time 1624468314.532189, type 1 (EV_KEY), code 45 (KEY_X), value 0
Event: time 1624468314.532189, -------------- SYN_REPORT ------------
```

I can see the device using xinput, however. My guess is that this is something regarding your system/setup. It's hard to tell though. Are your udev rules set up correctly? Which distro/version are you using? Would you mind sharing a code snippet? Judging from the data that you've provided it looks like you've done everything correctly in your code, but who knows...

I don't know if this helps, but a quick search brought up this (possibly) related issue: https://askubuntu.com/questions/1001044/ubuntu-17-10-mouse-not-showing-in-xinput. Maybe it's something along those lines. It may be worth checking your xorg log files to see whether anything shows up there.  

Let me know if you've made any progress analyzing this or whether you need further assistance.

Cheers,
Ben

**Comment by patrickcorrigan** [comment]
Thanks, Ben, I really appreciate the effort above. It's an instance on Google cloud so I wouldn't be surprised if Google disabled some udev rules in their default cloud images. Instead of wrestling with that, I'm now sending events directly to xwindows by using the c library libxdo and calling it from go :)

Thank you again. I really appreciate your help. Hope you're well
