### ISSUE TITLE
Add drawing tablet device and game controller

### ISSUE THREAD

**Issue by AndrusGerman** [bendahl/uinput#27]
There is the possibility that they add a device such as drawing tablet and game controller

**Comment by gitautas** [comment]
Hey, I'm using this package to have a virtual game pad, you can scavenge the code here: https://github.com/gitautas/veil/blob/main/helgi/pkg/uinput/gamepad.go

@bendahl if you change your mind on this issue I'm happy to clean up the code and make a PR.

**Comment by bendahl** [comment]
Hi there! 

@gitautas: First of all, thanks so much for offering your help on this! Help is always highly appreciated. I've looked at the code you linked to above and also at the HTML5-Spec. In addition, I did have a look through some Linux headers and discovered a couple of buttons and events that I wasn't aware of. @AndrusGerman: Seems like you're on to something regarding the game pad idea. 

I would generally appreciate a contribution, but am currently not 100% sure about the possible API and design of this new device. Looking at the specs, there are not just buttons, but also axis devices (two joysticks). This would certainly be something to be added down the road. Also, when using a real gamepad on my machine and intercepting the events, these aren't actually your regular key events, but rather "miscellaneous" type events. So all in all there are still quite a few questions on my end. 

Considering the above, I would suggest the following:

- I will create a package called "exp" for experimental features (analogous to the way the Go standard library handles this)
- @gitautas: Please use this package for your new device, once it is available. Also, some basic unit tests should also be included.
- Once everything is merged we can see how the API can/should be evolved. Having the "exp" package should give us some room to experiment with different API designs.

@gitautas: Does this sound reasonable to you? 

Cheers,
Ben

**Comment by gitautas** [comment]
@bendahl absolutely, I'll have some time next weekend to submit something for review. Thanks.

**Comment by AndrusGerman** [comment]
@gitautas  I was working on something similar to  https://github.com/gitautas/veil/blob/main/helgi/pkg/uinput/gamepad.go, I only managed to make the device and detect it in the control panel but I couldn't see why it didn't move. Now I see this and I know I was wrong (I still solved my problem with a joystick and it translated its movements to mouse and keyboard)

I am also willing to work on the implementation in which you will work, and add any functionality that is useful for this

**Comment by AndrusGerman** [comment]
>  Are these general ideas/suggestions or do you need these functionalities? Let me know what your thoughts are.

@bendahl I appreciate the interest,I was working on a mobile application to turn the phone into a remote or simply a control to manage your computer quickly
[GamePad](https://github.com/AndrusGerman/GamePadClient), [GamePadServer](https://github.com/AndrusGerman/GamePadLinuxServer) for these the functionality of a gamepad is quite useful,
So I will be aware of the work of gitautas and I hope to help.
It's about the drawing tablet, I have a project similar to [Weylus](https://github.com/H-M-H/Weylus) in mind. who seems to have achieved this, so I'm studying it on my own to try to bring it to this project

**Comment by bendahl** [comment]
@AndrusGerman: Sonds great! Thanks for the effort! I really appreciate this.

**Comment by bendahl** [comment]
Thanks again, @gitautas!

@AndrusGerman: Is there any progress on the drawing tablet?

**Comment by AndrusGerman** [comment]
@bendahl 
I did most of the implementation, but now I'm having problems since it seems to need a resolution parameter in the abs
![Screenshot_20220724_074138](https://user-images.githubusercontent.com/30560543/180645334-12d2a189-8cac-4b58-942b-2cc6132f90de.png)

In C the resolution is set like this, but I still didn't know how to implement it in go
```c
ioctl(fd, UI_SET_ABSBIT, abs_code)
struct uinput_abs_setup abs_setup;
memset(&abs_setup, 0, sizeof(abs_setup));
abs_setup.code = abs_code;
abs_setup.absinfo.value = 0;
abs_setup.absinfo.minimum = minimum;
abs_setup.absinfo.maximum = maximum;
abs_setup.absinfo.fuzz = 0;
abs_setup.absinfo.flat = 0;
abs_setup.absinfo.resolution = resolution;
ioctl(fd, UI_ABS_SETUP, &abs_setup)
```
Then out of nowhere [this](https://review.coreboot.org/plugins/gitiles/SerialTest/+/3a990b6ce5a7147d7021e80c3f63f69fb80465e7/chromiumos/tast/local/input/gamepad.go)  appears, is this chromium os? I have to read it a bit because it seems to have exactly what I need

**Comment by gitautas** [comment]
Ping me if you can't figure it out. In the mean time, I propose adding some more encapsulation to the gamepad. 

I think we should have a gamepad struct where we can access the buttons like so:
```go
gp.buttons.south.tap()
gp.sticks.r.move(0.24, 0.78)
```

**Comment by bendahl** [comment]
@AndrusGerman: Issuing ioctl calls can be done using the "ioctl" function provided by uinput.go (see line 224 ff.). What's currently missing is the Go translation of newer struct called "uinput_abs_setup" and defined in uinput.h. Note that part of the definition is located in input.h. I supect that what needs to be done is the following:

1. Create the new struct in uinputdefs.go (analogous to the already existing one).
2. Use this struct instead of "uinputUserDev" to initialize your device.

Also, a function similar to "createUsbDevice" will need to be created that takes the new struct as an argument. Please do not remove the current structure or function. This functionality should be kept for now in order to stay backwards compatible with older kernels. 

I hope this helps. Let me know if any further questions arise. 

Cheers
Ben

**Comment by AndrusGerman** [comment]
Please close this temporarily until you can continue, due to lack of time. I appreciate the effort and much progress was made in this book.
My branch is capable of creating a device, I only had the job of emitting the corresponding events. 
I ordered a drawing tablet from amazon, it will serve me perfectly to compare it with a real case
