### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by JohnGebbie** [bendahl/uinput#31]
I just wanted to say thank you, this library was exactly what I was looking for.
I wrote a program called [dotool](https://git.sr.ht/~geb/dotool) which is pretty much the library as a command,
and used it for my [voice input program](https://numen.johngebbie.com).
The examples are great and it just worked.

Many thanks

John

**Comment by bendahl** [comment]
Hi @JohnGebbie!

Thanks for the note! I'm glad to hear that the library is working well for your use case. 

Ben
