### ISSUE TITLE
Keyboard layouts?

### ISSUE THREAD

**Issue by JohnGebbie** [bendahl/uinput#32]
Hello, sorry if this isn't the place to ask but I'm not sure how to deal with keyboard layouts.
Someone showed me my [program](https://git.sr.ht/~geb/dotool) that uses this library types gobbledygook when you have a non-us keyboard layout set.
I found I could fix it in X by finding the virtual keyboard device ID with `xinput -list` and running `setxkbmap -device <ID> us`.

Is it possible to have the virtual keyboard device always set to the us layout?
I'd hope this would be at the linux/uinput level rather than be X specific but I don't know my stuff.

Thank you, I've really appreciated this library

**Comment by JohnGebbie** [comment]
I found you can use a udev like this:

    ACTION=="add", ATTRS{name}=="dotool keyboard", ENV{XKBLAYOUT}="us"

which works for X but not virtual consoles nor Wayland (sway).

**Comment by bendahl** [comment]
Hi @JohnGebbie,

I'm glad to hear that the library is of use to you! Sorry for the delay on my end. 

To answer your question: The uinput library is rather low level and only deals with keycodes as represented by the kernel, not keyboard-layout specific mappings. This is typically done at a higher level.

There is an answer on Stackoverflow that may shed some light on this: https://stackoverflow.com/questions/44218131/are-linux-input-h-keycodes-layout-independent

It would simply be beyond the scope of this library to handle different keyboard mappings. 

Although this is probably not the answer you were hoping to hear, I hope that this at least sheds some light on the matter. 

I'm closing the issue. Feel free to open another issue in case you encounter other issues.

Cheers
Ben
